apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: 138645654058.dkr.ecr.ap-south-1.amazonaws.com/gitaction:fb9f17efd6f689a410b205afff654afacdbd0566
        ports:
        - containerPort: 8080

