apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/gitaction:sha-123456
        ports:
        - containerPort: 8080
