name: Build & Push Python App Image

on:
 # push:
    # branches: [ main ]
  workflow_dispatch:   # allow manual trigger

permissions:
  packages: write    # required for pushing to GHCR
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_PAT }}

      - name: Define image metadata
        id: meta
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/renovate-repo
          TAG=${{ github.run_number }}

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & push image
        run: |
          docker build -t ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }} .
          docker push ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}

          # optional: also push :latest
          docker tag ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }} ${{ steps.meta.outputs.image }}:latest
          docker push ${{ steps.meta.outputs.image }}:latest

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Check out GitOps repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: nusrat-dops/k8-manifest
  #         token: ${{ secrets.GITOPS_PAT }}
  #         path: gitops

  #     - name: Setup Kustomize
  #       uses: imranismail/setup-kustomize@v2

  #     - name: Update kustomize overlay with new image
  #       working-directory: gitops/python-app/overlays/prod
  #       run: |
  #         IMAGE="${{ needs.build.outputs.image }}"
  #         TAG="${{ needs.build.outputs.tag }}"

  #         kustomize edit set image $IMAGE=$IMAGE:$TAG

  #         git config user.name "github-actions[bot]"
  #         git config user.email "github-actions[bot]@users.noreply.github.com"

  #         git add kustomization.yaml
  #         git commit -m "Update python-app image to $TAG" || echo "No changes"
  #         git push origin main

  #         echo "Updated kustomization.yaml:"
  #         cat kustomization.yaml
