name: Renovate

on:
  # push:
    # branches: [ main ]
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 * * * *"   # runs hourly, adjust as needed
env:
    LOG_LEVEL: debug
permissions:
  packages: write    # required for pushing to GHCR
  contents: read
  id-token: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.13
       
        with:
          token: ${{ secrets.GITOPS_PAT }}
          configurationFile: renovate.json
          repositories: nusrat-dops/renovate-repo
