name: Renovate

on:
  workflow_dispatch:
 # schedule:
   # - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.17
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
         
